name: deploy-online-code-editor

run-name: ${{ github.actor }} is deploying the code

on:
  push:
    branches:
      - main  # or 'master' or whichever branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Clean gh-pages old puild
        run: npx gh-pages-clean -d dist

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist

env:
 GH_TOKEN:${{secrets.GITHUB_TOKEN}}